HandicraftStore/Controllers/ExchangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HandicraftStore.Data;
using HandicraftStore.Models;
using System.Net;

namespace HandicraftStore.Controllers
{
    public class ExchangeController : Controller
    {
        private readonly ApplicationDbContext _context;
        //test commit second commit
        public ExchangeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Exchange
        public async Task<IActionResult> Index()
        {
              return _context.ExchangeRates != null ? 
                          View(await _context.ExchangeRates.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.ExchangeRate'  is null.");
        }

        public IActionResult Calculator()
        {
            List<ExchangeRate> rates = new List<ExchangeRate>();
            rates = _context.ExchangeRates.ToList();

            //ViewBag.TransferAmt = 0;
              ViewBag.rate = new SelectList(rates, "Id", "Country");
            return View() ;
                       // Problem("Entity set 'ApplicationDbContext.ExchangeRate'  is null.");
        }
       
       

        // GET: Exchange/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ExchangeRates == null)
            {
                return NotFound();
            }

            var exchangeRate = await _context.ExchangeRates
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exchangeRate == null)
            {
                return NotFound();
            }

            return View(exchangeRate);
        }
        [HttpPost]
        public JsonResult GetRates(int? id)
        {
            var exchangeRate = _context.ExchangeRates
               .FirstOrDefault(m => m.Id == id);
            if (exchangeRate == null)
            {
                //return NotFound();
            }
            return Json(exchangeRate.Rate);
        }
        //public ActionResult GetRate(int? id)
        //{
        //    //if (id == null)
        //    //{
        //    //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    //}

        //    var exchangeRate =  _context.ExchangeRates
        //        .FirstOrDefault(m => m.Id == id);
        //    if (exchangeRate == null)
        //    {
        //        return NotFound();
        //    }
        //    return View("ViewPartOd", po);
        //}

        // GET: Exchange/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Agent()
        {
            return View();
        }

        // POST: Exchange/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Country,Rate")] ExchangeRate exchangeRate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(exchangeRate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(exchangeRate);
        }

        // GET: Exchange/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ExchangeRates == null)
            {
                return NotFound();
            }

            var exchangeRate = await _context.ExchangeRates.FindAsync(id);
            if (exchangeRate == null)
            {
                return NotFound();
            }
            return View(exchangeRate);
        }

        // POST: Exchange/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Country,Rate")] ExchangeRate exchangeRate)
        {
            if (id != exchangeRate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(exchangeRate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExchangeRateExists(exchangeRate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(exchangeRate);
        }

        // GET: Exchange/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ExchangeRates == null)
            {
                return NotFound();
            }

            var exchangeRate = await _context.ExchangeRates
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exchangeRate == null)
            {
                return NotFound();
            }

            return View(exchangeRate);
        }

        // POST: Exchange/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ExchangeRates == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ExchangeRate'  is null.");
            }
            var exchangeRate = await _context.ExchangeRates.FindAsync(id);
            if (exchangeRate != null)
            {
                _context.ExchangeRates.Remove(exchangeRate);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExchangeRateExists(int id)
        {
          return (_context.ExchangeRates?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HandicraftStore/Views/Exchange/Agent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="bg-gray-100" id="send-now-option-panel">
    <div class="max-w-7xl mx-auto pb-0 py-5 px-4 sm:px-6 lg:px-8">
        <h1 class="text-center text-4xl font-bold klickex-blue-text">
            Select the Mobile Network you want to send to
        </h1>

        <div class="mt-6 grid grid-cols-1 gap-2 sm:grid-cols-1 md:grid-cols-8">
            <div class="col-span-1 flex justify-center sm:mb-8 md:col-span-2">
                <a asp-action="Calculator" asp-controller="Exchange">
                    <img class="h-24 mt-10 md:h-20 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110" src="/images/digicel.png" alt="Digicel">
                </a>
            </div>
            <div class="col-span-1 flex justify-center sm:mb-8 md:col-span-2">
                <a asp-action="Calculator" asp-controller="Exchange">
                    <img class="h-24 mt-10 md:h-20 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110" src="/images/vodafone.png" alt="Vodafone">
                </a>
            </div>

            
        </div>
    </div>
</div>

HandicraftStore/Views/Exchange/Calculator.cshtml
@model HandicraftStore.Models.ExchangeRate
@{
    ViewData["Title"] = "GotoCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Money Transfer</h4>

 
    <table>
        <tr>
            <td>Send money to</td>
            <td>@Html.DropDownList("Id", ViewBag.rate as SelectList,"--Select--",  new {  id="Country", style="width:100px;" })  </td>
        </tr>
        <tr>
            <td>Exchange Rate</td>
            <td><input name="Rate" type="number" id="Rate" readonly style="width:100px" /></td>
        </tr>
        <tr>
            <td>Enter Amount in NZ dollars</td>
            <td>@Html.TextBox("amount", 0.00, new { required = "required", type="number", style="width:100px" })</td>
        </tr>
    </table>
    <br />
    <input type="button" value="Calculate" onclick="CalcAmt();" style="font-weight: bolder; font-family:Calibri; color:white; Background:red" />
 <br />
    <br />
    <div class="summary" style="display:none; font-weight:bold; font-family:Calibri; color:#616161">
    <table>
        <thead style="column-span:2;">Summary</thead>
        <tr>
            <td>Amount to Transfer </td>
                <td id="TransfrAmt"></td>
        </tr>
        <tr>
            <td>Exchange Rate</td>
            <td id="ExchangeRate"></td>
        </tr>
        <tr>
            <td>Transfer Fee</td>
            <td>$2.00 NZD</td>
        </tr>
            <tr style="color:red">
            <td>Total Cost</td>
            <td id="Totalcost"></td>
        </tr>
    </table>
</div>

@section Scripts
{
    <script>
        function CalcAmt() {
          
            $("#amount").removeClass('errorClass');
            if ($("#amount").val() == 0)
            {
                $(".summary").hide();
                $("#amount").addClass('errorClass');
            }
            else
            {
                $(".summary").show();
                $('#TransfrAmt').text("$" + $("#amount").val() + " NZD");
                $('#ExchangeRate').text($("#Rate").val());
                var amt = ($("#Rate").val() * $("#amount").val()) + 2.0;
                $('#Totalcost').text("$" + amt);
                $("#ReceivedAmt").val($("#Rate").val() * $("#amount").val());
            }
           
        }
        $("#Country").on('change', function () {
            $("#Country").removeClass('errorClass');
            var getValue = $(this).val();
            if (getValue==0)
            {
                $("#Country").addClass('errorClass');
               // alert("test");
               }
            else{

                $.ajax({
                    url: "@Url.Action("GetRates" , "Exchange")",
                    data: { id: getValue },
                    type: "Post",
                    dataType: "html",

                    success: function (data) {
                        debugger
                        data = JSON.parse(data);
                        $("#Rate").val(data);

                    }
                    ,
                    error: function (data) {
                        alert("error", data.responseText);
                    }
                });
            }

                
           
        });

    </script>
  
}

HandicraftStore/Views/Exchange/Create.cshtml
@model HandicraftStore.Models.ExchangeRate

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Create ExchangeRate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label"></label>
                <input asp-for="Rate" class="form-control"  />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />|
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

HandicraftStore/Views/Exchange/Delete.cshtml
@model HandicraftStore.Models.ExchangeRate

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <h4>Delete ExchangeRate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

HandicraftStore/Views/Exchange/Details.cshtml
@model HandicraftStore.Models.ExchangeRate

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>ExchangeRate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HandicraftStore/Views/Exchange/Edit.cshtml
@model HandicraftStore.Models.ExchangeRate

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Edit ExchangeRate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label"></label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />|
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

HandicraftStore/Views/Exchange/Index.cshtml
@model IEnumerable<HandicraftStore.Models.ExchangeRate>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Exchange Rate</h4>

<p>
    <a asp-action="Create" class="btn btn-sm btn-primary ml-1">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rate)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-info">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger ml-1">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>