HandicraftStore/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;

namespace HandicraftStore.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        public string Description { get; set; }
        [Column(TypeName ="SmallMoney")]
        [Required]
        public decimal Amount { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public IFormFile CraftImage { get; set; }
        public virtual List<Orders> ProductOrder { get; set; }
        [NotMapped]
        public object GetById { get; internal set; }
        [NotMapped]
        public string imagepath { get; set; }
        [NotMapped]
        public int Quantity { get; set; }
    }
}

HandicraftStore/Controllers/ProductController.cs
using HandicraftStore.Interface;
using HandicraftStore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.ComponentModel.DataAnnotations.Schema;

namespace HandicraftStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProduct _prod;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProductController(IProduct product, IWebHostEnvironment webHost)
        {
            webHostEnvironment = webHost;
            _prod = product;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var prod = _prod.GetAll();
            return View(prod);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Product prod = new Product();
            return View(prod);
        }
        [HttpPost]
        public IActionResult Create(Product prod)
        {
            string uniqueFileName = UploadedFile(prod);
            prod.ImageUrl = uniqueFileName;
            _prod.Insert(prod);
            _prod.Save();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var prod = _prod.GetById(Id);
            _prod.Delete(prod);
            _prod.Save();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult Delete(Product prod)
        {
            _prod.Delete(prod);
            _prod.Save();
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var craft = _prod.GetById(Id);
            craft.imagepath = craft.ImageUrl;
            return View(craft);
        }
       
        public string GetUrl(int Id)
        {
            var craft = _prod.GetById(Id);
            return craft.ImageUrl; 
        }
        [HttpPost]
        public IActionResult Edit(Product prod)
        {
            
            string uniqueFileName;
           
            if (prod.ImageUrl != null)
            {
                uniqueFileName = UploadedFile(prod);
                
            }
            else
            {
                uniqueFileName = prod.imagepath;// GetUrl(prod.Id);
            }
            
            prod.ImageUrl = uniqueFileName;
            _prod.Update(prod);
            _prod.Save();
            return RedirectToAction("Index", "Product");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        private string UploadedFile(Product prod)
        {
            string uniqueFileName = null;
            if (prod.CraftImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + prod.CraftImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    prod.CraftImage.CopyTo(fileStream); 
                }
            }
            return uniqueFileName;

        }
    }
   
}

HandicraftStore/Views/Shared/Components/ImageUploader/ImageUploaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace HandicraftStore.Views.Shared.Components.ImageUploader
{
    public class ImageUploaderViewComponent:ViewComponent
    {
        public ImageUploaderViewComponent()
        {
        }
        public IViewComponentResult Invoke(string FieldName)
        {
            return View("Default", FieldName);
        }

       

    }
}

HandicraftStore/Views/Product/Create.cshtml
@model HandicraftStore.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

            <h4>Create Product</h4>


             <form enctype="multipart/form-data" asp-action="Create">
                 <div class="row">
                    <div class="col-md-6">
                        <section>
                             <div class="form-group col-md-6 ">
                        <label asp-for="Description" class="control-label"></label>
                        <input  asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" type="number"/>
                        <span asp-validation-for="Amount" class="text-danger" ></span>
                    </div>
                   

                        </section>
                    </div>
                    <div class="col-md-6 col-md-offset-2">
                        <section>
                              <vc:image-uploader field-name="@nameof(Model.CraftImage)">
                        </vc:image-uploader>
                        </section>
                    </div>
                </div>

                @* <div class="row">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-md-6 ">
                        <label asp-for="Description" class="control-label"></label>
                        <input  asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                     <div class="col-md-6">
                        <vc:image-uploader field-name="@nameof(Model.CraftImage)">
                        </vc:image-uploader>
                    </div>
                   
                 </diV>*@
 
                       @* <div class="form-group">
                        <label asp-for="CraftImage" class="control-label"></label>
                        <input asp-for="CraftImage" accept="image/*" />
                        <span asp-validation-for="CraftImage" class="text-danger"></span>
                        </div>*@
                    @* <div class="form-group col-md-6">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>*@
                   
                    <div class="col-12 btn-group">
                        
                        <div class="form-group">
                             <input type="submit" value="Create" class="btn btn-primary" />|
                               <a asp-action="Index" class="btn btn-secondary">Back</a>
                        </div>
                    </div>

            </form>



<br/>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(".custom-file-input").on("change",function(){
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>

}

HandicraftStore/Views/Product/Details.cshtml
@model HandicraftStore.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HandicraftStore/Views/Product/Edit.cshtml
@model HandicraftStore.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />


            <h4>Edit Product</h4>

            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="row">
                    <div class="form-group col-md-8">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                    <div class="col-md-6">
                      @*  <img src="~/images/Model.ImageUrl" class="rounded-circle" height="40" width="40" asp-append-version="true" />*@
                        <img decoding="async" src="@("~/images/"+Model.ImageUrl)" asp-append-version="true" width="250px" height="250px" />
                        <input asp-for="imagepath" style="display:none;" />
                        <vc:image-uploader field-name="@nameof(Model.CraftImage)">
                        </vc:image-uploader>
                    </div>
            
                    <div class="col-12 btn-group">
                        <div class="col-1 form-group text-right p-2">
                            <a asp-action="Index" class="btn btn-secondary">Back</a>
                        </div>
                        <div class="col-1 form-group text-right p-2">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                        <div class="col-10 form-group text-right p-2">
                        </div>
                    </div>

              
                </div>
                   
                 </form>

<div class="row">
    <div class="col-md-4">
       
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

HandicraftStore/Views/Product/Index.cshtml
@model IEnumerable<HandicraftStore.Models.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h5>Manage Handicraft</h5>
<br />
<p>
    <a asp-action="Create" class="btn btn-sm btn-primary ml-1">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th> </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
       
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="~/Images/@item.ImageUrl" style="width:75px;height:75px;"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-info">Edit</a> |
               @* <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary ml-1">Details</a> |*@
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger ml-1">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>